site_name: Software + ML
site_url: https://softwareplusml.baluyotraf.com
site_description: Stories and Codes from Research to Production
repo_url: https://github.com/baluyotraf/softwareplusml
repo_name: baluyotraf/softwareplusml
edit_uri: ""
copyright: Copyright &copy; 2024 Raffaello Baluyot

nav:
  - Home: index.md
  - Stories:
      - stories/index.md
  - Projects:
      - Alternative Queries: projects/altqq.md
      - Education: projects/education.md

plugins:
  - include-markdown
  - search
  - social
  - blog:
      blog_dir: stories

markdown_extensions:
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: light blue
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/baluyotraf/
      name: baluyotraf
    - icon: fontawesome/brands/github
      link: https://github.com/baluyotraf
      name: baluyotraf
